version: '3.8'

services:
  django:
    build: ./movie_listing
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./movie_listing/:/usr/src/movie_listing/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - selenium-hub
      - db
  chrome:
    image: selenium/node-chrome:4.7.2-20221219
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  # chrome_video:
  #   image: selenium/video:ffmpeg-4.3.1-20221219
  #   volumes:
  #     - /tmp/videos:/videos
  #   depends_on:
  #     - chrome
  #   environment:
  #     - DISPLAY_CONTAINER_NAME=chrome
  #     - FILE_NAME=chrome_video.mp4
  selenium-hub:
    image: selenium/hub:4.7.2-20221219
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=movie_listing
      - POSTGRES_PASSWORD=movie_listing
      - POSTGRES_DB=movie_listing_dev

volumes:
  postgres_data: