version: '3.8'

services:
  django:
    build:
      context: ./fancy_web_scrapping
      dockerfile: Dockerfile.prod
    command: gunicorn fancy_web_scrapping.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/fancy_web_scrapping/django/staticfiles
      - media_volume:/home/fancy_web_scrapping/django/mediafiles
    expose:
      - 8000
    environment:
      - SERVICE_NAME=django
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - db
      - selenium-hub
  celery:
    build: ./fancy_web_scrapping
    command: celery -A fancy_web_scrapping worker --loglevel=info --concurrency 10 -E --uid=nobody --gid=nogroup
    volumes:
      - ./fancy_web_scrapping/:/usr/src/fancy_web_scrapping/
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - redis
  dashboard:
    build: ./fancy_web_scrapping
    command: celery flower -A fancy_web_scrapping --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./.env.dev
    depends_on:
      - django
      - redis
      - celery
  redis:
    image: redis:7-alpine 
    expose:
        - 6379
    deploy:
      resources:
        limits:
          memory: 512M
  chrome:
    image: selenium/node-chrome:4.7.2-20221219
    shm_size: 4gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=10
  # chrome_video:
  #   image: selenium/video:ffmpeg-4.3.1-20221219
  #   volumes:
  #     - /tmp/videos:/videos
  #   depends_on:
  #     - chrome
  #   environment:
  #     - DISPLAY_CONTAINER_NAME=chrome
  #     - FILE_NAME=chrome_video.mp4
  selenium-hub:
    image: selenium/hub:4.7.2-20221219
    container_name: selenium-hub
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    expose:
      - 5432
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/fancy_web_scrapping/django/staticfiles
      - media_volume:/home/fancy_web_scrapping/django/mediafiles
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:
  media_volume: