# Generated by Django 4.1.5 on 2023-01-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Name')),
                ('address', models.CharField(max_length=255, null=True, verbose_name='Address')),
                ('url', models.URLField(null=True, verbose_name='URL')),
            ],
        ),
    ]
