# Generated by Django 4.0.6 on 2023-01-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='sessions',
            field=models.JSONField(null=True, verbose_name='Sessions'),
        ),
    ]
